import type { NextPage } from "next";
import Head from "next/head";
import { css } from "@emotion/react";
import { createBoard } from "../domains/models/board";
import { printBoard } from "../domains/helpers/printer";
import { getBoardWithCandidates } from "../domains/helpers/solve";
import { Backtrack } from "../domains/helpers/backtrack";

const Home: NextPage = () => {
  const container = css`
    background-color: red;
  `;

  const input =
    "310004069000000200008005040000000005006000017807030000590700006600003050000100002";
  const board = createBoard(input);
  printBoard(board);
  const answerBoard = new Backtrack().solve(board);
  printBoard(answerBoard);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={container}>Emotion Sample</div>
    </div>
  );
};

export default Home;
