import type { NextPage } from "next";
import Head from "next/head";
import { css } from "@emotion/react";
import { createBoard } from "../domains/models/board";
import { printBoard } from "../domains/helpers/printer";
import { Backtracking } from "../domains/helpers/backtracking";

const Home: NextPage = () => {
  const container = css`
    background-color: red;
  `;

  const input =
    // "310004069000000200008005040000000005006000017807030000590700006600003050000100002";
    // "010020300002003040050000006004700050000100003070068000300004090000600104006000000";
    "010020300002003040080000006004700030000600008070098000300004090000800104006000000";
  const board = createBoard(input);
  printBoard(board);
  const answerBoard = new Backtracking().solve(board);
  printBoard(answerBoard);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={container}>Emotion Sample</div>
    </div>
  );
};

export default Home;
