import type { NextPage } from "next";
import Head from "next/head";
import { css } from "@emotion/react";
import { Board } from "../models/Board";

const Home: NextPage = () => {
  const container = css`
    background-color: red;
  `;

  const input =
    "310004069000000200008005040000000005006000017807030000590700006600003050000100002";
  const board = Board.from(input);
  console.log(board.toString());

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={container}>Emotion Sample</div>
    </div>
  );
};

export default Home;
